{
 "title": "Self Monitoring Grafana",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "NS",
    "query": {
     "query": "label_values(grafana_build_info,namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$NS\",pod=~\".*grafana.*\"},container)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(grafana_build_info,version)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(grafana_build_info,pod)"
    }
   },
   {
    "name": "grafpvc",
    "query": {
     "query": "label_values(persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_info{container=\"grafana\",namespace=\"$NS\",pod=\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_active_users{namespace=\"$NS\"}"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_users{namespace=\"$NS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Folders",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_folder{namespace=\"$NS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build_Info",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_build_info{namespace=\"$NS\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Active Editors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_active_editors{namespace=\"$NS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Dashboards",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{namespace=\"$NS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory_Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg((avg (container_memory_working_set_bytes{pod=\"$pod\",container=\"$container\"}) by (container , pod ))/ on (container , pod)(avg (container_spec_memory_limit_bytes>0 ) by (container, pod))*100)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU_Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\",container=\"$container\"}[5m])) by (pod, container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"$pod\",namespace=\"$NS\",container=\"$container\",unit=\"core\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "grafana-backup-volume Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$NS\", persistentvolumeclaim=\"grafana-backup-volume\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$NS\", persistentvolumeclaim=\"grafana-backup-volume\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$NS\", persistentvolumeclaim=\"grafana-backup-volume\"})\n* 100)\n"
    }
   ]
  },
  {
   "title": "grafana-pvc Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$NS\", persistentvolumeclaim=\"$grafpvc\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$NS\", persistentvolumeclaim=\"$grafpvc\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$NS\", persistentvolumeclaim=\"$grafpvc\"})\n* 100)\n"
    }
   ]
  }
 ]
}